################################################################################
## Mode choice
################################################################################

# An engine can run in two modes: single mode, runner mode or network mode.
# SCHEDULER: this is a scheduler.
# RUNNER: this not a scheduler but simply a remote execution agent.
# Default: SCHEDULER
# jChronix.mode = RUNNER

################################################################################
## Cluster parameters (Scheduler mode only)
################################################################################

# Parameters in this section must be ignored if you are running a single
# lone scheduler.
# They are only needed for networks of schedulers.

# The name of the engine. Must be the same as in the environment metadata.
# This name must be unique in your jChronix cluster.
# If not set, the scheduler will consider it is running in single scheduler
# mode (i.e. no network of schedulers)
# Defaults to: not set.
# jChronix.cluster.node.name = marsu

# This is used for automatic new scheduler node deployment.
# At startup, the engine will request all metadata (i.e. network of scheduler
# description + application plans) from another node.
# Usually this will be the console node.
# This is not compulsory - including the NETWORK file in your deployment
# also works great.
# jChronix.cluster.bootstrap.dns = console.local
# jChronix.cluster.bootstrap.port = 1789


################################################################################
## [Single node] or [First node in network of schedulers] network bootstrap
################################################################################

# DNS and ports to listen to are normally described inside the ENVIRONMENT
# file. This file is stored inside the metadata database (the metabase).
# However, on first boot, the metabase is yet to be created, so these values
# are used to create the metabase.
# These values are only used if the ENVIRONMENT file does not exist AND if
# jChronix.cluster.bootstrap.dns is not set.
# On subsequent boots, the ENVIRONMENT file will exist and these values will be
# ignored.
jChronix.startup.bootstrap.dns = localhost
jChronix.startup.bootstrap.qPort = 1789
jChronix.startup.bootstrap.wsPort = 1790


################################################################################
## Paths
################################################################################

# The directory in which jChronix will store its databases, its plan
# configuration, its logs as well as the job logs.
# This is the metabase. It cannot be shared between nodes running on the same
# server.
# It will be created if it does not exist - just be wary of permissions.
# Default: ./metabase (where . is the install directory)
# jChronix.repository.path = ./metabase


################################################################################
## Log
################################################################################

# The main log level. Choice between TRACE, DEBUG, INFO, WARN, ERROR.
# Default: INFO
jChronix.log.level = INFO


################################################################################
## Debug engine parameters (only if engine is started)
################################################################################


################################################################################
## Runner (only if runner started)
################################################################################

# The max number of jobs running at a the same time
# Default is 5
jChronix.runner.maxjobs = 1
